import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from "@/app/providers"
import Header from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,showHeader = true,
}: {
  children: React.ReactNode ,
  showHeader? :boolean,
}) {



  return (
    <html lang="en">
      <body className={inter.className}>
          <div>
            <Providers>
            {showHeader && <Header/>}
            {children}
            
            </Providers>
          </div>
        </body>
    </html>
  )
}
